services:
  master-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master-dashboard
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.master-dash.rule=Host(`dash.anyemp.com`)"
      - "traefik.http.routers.master-dash.entrypoints=https"
      - "traefik.http.routers.master-dash.tls=true"
      - "traefik.http.routers.master-dash.tls.certresolver=letsencrypt"
      - "traefik.http.services.master-dash.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  traefik-public:
    external: true
