services:
  master-dashboard:
    image: global-dashboard:latest
    container_name: master-dashboard
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.master-dashboard.rule=Host(`dash.anyemp.com`)"
      - "traefik.http.routers.master-dashboard.entrypoints=https"
      - "traefik.http.routers.master-dashboard.tls=true"
      - "traefik.http.routers.master-dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.master-dashboard.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  traefik-public:
    external: true
